[package]
name = "tensor_transforms"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Jack Stade <jack.stade@gmail.com>"]

[dependencies]
tracked_mem = {git = "https://github.com/JackStade/tracked-mem-rs.git"}